"""empty message

Revision ID: ddfe57fc7e9c
Revises: 
Create Date: 2026-03-05 10:17:44.465265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'ddfe57fc7e9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mission',
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mission'))
    )
    op.create_table('team',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('headquarters', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team'))
    )
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_name'), ['name'], unique=False)

    op.create_table('hero',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_hero_team_id_team')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hero'))
    )
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hero_age'), ['age'], unique=False)
        batch_op.create_index(batch_op.f('ix_hero_name'), ['name'], unique=False)

    op.create_table('heromissionlink',
    sa.Column('hero_id', sa.Uuid(), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['hero_id'], ['hero.id'], name=op.f('fk_heromissionlink_hero_id_hero')),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], name=op.f('fk_heromissionlink_mission_id_mission')),
    sa.PrimaryKeyConstraint('hero_id', 'mission_id', name=op.f('pk_heromissionlink'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('heromissionlink')
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hero_name'))
        batch_op.drop_index(batch_op.f('ix_hero_age'))

    op.drop_table('hero')
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_name'))

    op.drop_table('team')
    op.drop_table('mission')
    # ### end Alembic commands ###
